// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_arrivals_cpp
DataFrame generate_arrivals_cpp(double arrival_rate, double sim_duration, NumericVector urgency_probs);
RcppExport SEXP _ERsim_generate_arrivals_cpp(SEXP arrival_rateSEXP, SEXP sim_durationSEXP, SEXP urgency_probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type arrival_rate(arrival_rateSEXP);
    Rcpp::traits::input_parameter< double >::type sim_duration(sim_durationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type urgency_probs(urgency_probsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_arrivals_cpp(arrival_rate, sim_duration, urgency_probs));
    return rcpp_result_gen;
END_RCPP
}
// summary_stats_cpp
NumericVector summary_stats_cpp(NumericVector x, double quantile_p);
RcppExport SEXP _ERsim_summary_stats_cpp(SEXP xSEXP, SEXP quantile_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type quantile_p(quantile_pSEXP);
    rcpp_result_gen = Rcpp::wrap(summary_stats_cpp(x, quantile_p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ERsim_generate_arrivals_cpp", (DL_FUNC) &_ERsim_generate_arrivals_cpp, 3},
    {"_ERsim_summary_stats_cpp", (DL_FUNC) &_ERsim_summary_stats_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ERsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
