# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Arrival Events for the ER Simulation
#'
#' Uses an exponential inter-arrival process (Poisson arrivals) to produce a
#' data.frame of arrival events with assigned urgency levels. This is the
#' performance-critical sampling loop that benefits from C++ execution.
#'
#' @param arrival_rate  Double. Patients per minute (lambda for the exponential).
#' @param sim_duration  Double. Total simulation duration in minutes.
#' @param urgency_probs NumericVector of length 3. Probabilities for urgency
#'   levels 1 (Critical), 2 (Urgent), 3 (Standard). Must sum to 1.
#'
#' @return A data.frame with columns:
#' \describe{
#'   \item{type}{Character "ARRIVAL" for every row.}
#'   \item{time}{Numeric arrival time (minutes from simulation start).}
#'   \item{patient_id}{NA_character_ — filled in by R when processed.}
#'   \item{urgency_level}{Integer 1, 2, or 3.}
#' }
#' @export
generate_arrivals_cpp <- function(arrival_rate, sim_duration, urgency_probs) {
    .Call('_ERsim_generate_arrivals_cpp', PACKAGE = 'ERsim', arrival_rate, sim_duration, urgency_probs)
}

#' Compute Summary Statistics Over a Numeric Vector (Vectorized C++)
#'
#' Fast computation of mean, median, and specified quantile for a numeric
#' vector. Used internally to accelerate KPI calculations on large patient logs.
#'
#' @param x       NumericVector. Input values (e.g., wait times).
#' @param quantile_p Double. Quantile to compute, between 0 and 1. Default 0.95.
#'
#' @return A named NumericVector with elements: \code{mean}, \code{median},
#'   \code{quantile}.
#' @export
summary_stats_cpp <- function(x, quantile_p = 0.95) {
    .Call('_ERsim_summary_stats_cpp', PACKAGE = 'ERsim', x, quantile_p)
}

